name: ServiceNow DevOps Change Automation

on: push

jobs:
  
  deploy:
      name: deploy
      runs-on: ubuntu-latest
      steps:     
        - name: ServiceNow Change
          uses: ServiceNow/servicenow-devops-change@v4.0.0
          with:
            # ServiceNow Instance URL
            instance-url: ${{ secrets.SN_INSTANCE_URL }}
            # Devops Integration User Name
            devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
            # Devops Integration User Password
            devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
            # Devops Integration Token
            #devops-integration-token: # optional
            # Orchestration Tool Id
            tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
            # Display Name of the Job
            job-name: Test Job
            # Github Context
            context-github: ${{ toJSON(github) }}
            # The max. time in seconds to wait until the action should fail.
            timeout: 3600 # optional, default is 3600
            # The time in seconds to wait between trying the API.
            interval: 100 # optional, default is 100
            # The customized inputs to create change with the requested details.
            change-request: '{"setCloseCode":"true","autoCloseChange":true,"attributes":{"short_description":"Automated Software Deployment","description":"Automated Software Deployment.","implementation_plan":"Software update is tested and results can be found in Test Summaries Tab; When the change is approved the implementation happens automated by the CICD pipeline within the change planned start and end time window.","backout_plan":"When software fails in production, the previous software release will be re-deployed.","test_plan":"Testing if the software was successfully deployed"}}'
            # The max. time in seconds to wait until change created.
            changeCreationTimeOut: 3600 # optional, default is 3600
            # This value will be used to resume or abort the pipeline if the change is not created within the mentioned time period in changeCreationTimeOut. 
            abortOnChangeCreationFailure: true # optional, default is true
            # This value will be used to resume or abort the pipeline after a timeout has occurred in case a change step is still in a pending state.
            abortOnChangeStepTimeout: true # optional, default is true
            # The customized inputs to process deployment gate job related change.
            #deployment-gate: # option
        - name: Output of Change Creation
          run: echo "change-request-number = ${{ steps.create.outputs.change-request-number }} and change-request-sys-id = ${{ steps.create.outputs.change-request-sys-id }} " >> $GITHUB_OUTPUT
    
